apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "publisher.fullname" . }}--scholarly-articles
  labels:
    {{- include "publisher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "publisher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "publisher.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.articleStore.repository }}:latest"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
