apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--scholarly-articles
  labels:
    {{- include "publisher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "publisher.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scholarly-articles
  template:
    metadata:
      labels:
        {{- include "publisher.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scholarly-articles
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.articleStore.repository }}:latest"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
